server:
  maxThreads: 256
  minThreads: 256
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

logging:
  level: DEBUG
  # Logger-specific levels.
  loggers:
    com.phonepe.payments: DEBUG
    org.hibernate: ERROR

  appenders:
    - type: console
      threshold: INFO                                                         `
      timeZone: IST
      logFormat: "%(%-5level) [%date] [%thread] [%logger{0}]: %message%n"